[profile.default]
verbosity = 2
fs_permissions = [{ access = "read", path = "./" }]

## add huff support
ffi = true

## set only when the `hardhat` profile is selected
[profile.hardhat]
src = "contracts"
out = "artifacts"
libs = ["node_modules"]
fs_permissions = [{ access = "read", path = "./" }]
